# CMAKE generated file: DO NOT EDIT!
# Generated by "Unix Makefiles" Generator, CMake Version 3.0

# Default target executed when no arguments are given to make.
default_target: all
.PHONY : default_target

# Allow only one "make -f Makefile2" at a time, but pass parallelism.
.NOTPARALLEL:
.PHONY : .NOTPARALLEL

#=============================================================================
# Special targets provided by cmake.

# Disable implicit rules so canonical targets will work.
.SUFFIXES:

# Remove some rules from gmake that .SUFFIXES does not remove.
SUFFIXES =

.SUFFIXES: .hpux_make_needs_suffix_list

# Suppress display of executed commands.
$(VERBOSE).SILENT:

# A target that is always out of date.
cmake_force:
.PHONY : cmake_force

#=============================================================================
# Set environment variables for the build.

# The shell in which to execute make rules.
SHELL = /bin/sh

# The CMake executable.
CMAKE_COMMAND = /usr/bin/cmake

# The command to remove a file.
RM = /usr/bin/cmake -E remove -f

# Escaping for special characters.
EQUALS = =

# The top-level source directory on which CMake was run.
CMAKE_SOURCE_DIR = /home/ian/workspace/Firmware

# The top-level build directory on which CMake was run.
CMAKE_BINARY_DIR = /home/ian/workspace/Firmware

#=============================================================================
# Targets provided globally by CMake.

# Special rule for the target edit_cache
edit_cache:
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --cyan "No interactive CMake dialog available..."
	/usr/bin/cmake -E echo No\ interactive\ CMake\ dialog\ available.
.PHONY : edit_cache

# Special rule for the target edit_cache
edit_cache/fast: edit_cache
.PHONY : edit_cache/fast

# Special rule for the target install
install: preinstall
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --cyan "Install the project..."
	/usr/bin/cmake -P cmake_install.cmake
.PHONY : install

# Special rule for the target install
install/fast: preinstall/fast
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --cyan "Install the project..."
	/usr/bin/cmake -P cmake_install.cmake
.PHONY : install/fast

# Special rule for the target install/local
install/local: preinstall
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --cyan "Installing only the local directory..."
	/usr/bin/cmake -DCMAKE_INSTALL_LOCAL_ONLY=1 -P cmake_install.cmake
.PHONY : install/local

# Special rule for the target install/local
install/local/fast: install/local
.PHONY : install/local/fast

# Special rule for the target install/strip
install/strip: preinstall
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --cyan "Installing the project stripped..."
	/usr/bin/cmake -DCMAKE_INSTALL_DO_STRIP=1 -P cmake_install.cmake
.PHONY : install/strip

# Special rule for the target install/strip
install/strip/fast: install/strip
.PHONY : install/strip/fast

# Special rule for the target list_install_components
list_install_components:
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --cyan "Available install components are: \"Unspecified\""
.PHONY : list_install_components

# Special rule for the target list_install_components
list_install_components/fast: list_install_components
.PHONY : list_install_components/fast

# Special rule for the target package
package: preinstall
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --cyan "Run CPack packaging tool..."
	/usr/bin/cpack --config ./CPackConfig.cmake
.PHONY : package

# Special rule for the target package
package/fast: package
.PHONY : package/fast

# Special rule for the target package_source
package_source:
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --cyan "Run CPack packaging tool for source..."
	/usr/bin/cpack --config ./CPackSourceConfig.cmake /home/ian/workspace/Firmware/CPackSourceConfig.cmake
.PHONY : package_source

# Special rule for the target package_source
package_source/fast: package_source
.PHONY : package_source/fast

# Special rule for the target rebuild_cache
rebuild_cache:
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --cyan "Running CMake to regenerate build system..."
	/usr/bin/cmake -H$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR)
.PHONY : rebuild_cache

# Special rule for the target rebuild_cache
rebuild_cache/fast: rebuild_cache
.PHONY : rebuild_cache/fast

# Special rule for the target test
test:
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --cyan "Running tests..."
	/usr/bin/ctest --force-new-ctest-process $(ARGS)
.PHONY : test

# Special rule for the target test
test/fast: test
.PHONY : test/fast

# The main all target
all: cmake_check_build_system
	$(CMAKE_COMMAND) -E cmake_progress_start /home/ian/workspace/Firmware/CMakeFiles /home/ian/workspace/Firmware/CMakeFiles/progress.marks
	$(MAKE) -f CMakeFiles/Makefile2 all
	$(CMAKE_COMMAND) -E cmake_progress_start /home/ian/workspace/Firmware/CMakeFiles 0
.PHONY : all

# The main clean target
clean:
	$(MAKE) -f CMakeFiles/Makefile2 clean
.PHONY : clean

# The main clean target
clean/fast: clean
.PHONY : clean/fast

# Prepare targets for installation.
preinstall: all
	$(MAKE) -f CMakeFiles/Makefile2 preinstall
.PHONY : preinstall

# Prepare targets for installation.
preinstall/fast:
	$(MAKE) -f CMakeFiles/Makefile2 preinstall
.PHONY : preinstall/fast

# clear depends
depend:
	$(CMAKE_COMMAND) -H$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR) --check-build-system CMakeFiles/Makefile.cmake 1
.PHONY : depend

#=============================================================================
# Target rules for targets named __nuttx_copy_px4fmu-v2

# Build rule for target.
__nuttx_copy_px4fmu-v2: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 __nuttx_copy_px4fmu-v2
.PHONY : __nuttx_copy_px4fmu-v2

# fast build rule for target.
__nuttx_copy_px4fmu-v2/fast:
	$(MAKE) -f CMakeFiles/__nuttx_copy_px4fmu-v2.dir/build.make CMakeFiles/__nuttx_copy_px4fmu-v2.dir/build
.PHONY : __nuttx_copy_px4fmu-v2/fast

#=============================================================================
# Target rules for targets named __nuttx_patch_px4fmu-v2

# Build rule for target.
__nuttx_patch_px4fmu-v2: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 __nuttx_patch_px4fmu-v2
.PHONY : __nuttx_patch_px4fmu-v2

# fast build rule for target.
__nuttx_patch_px4fmu-v2/fast:
	$(MAKE) -f CMakeFiles/__nuttx_patch_px4fmu-v2.dir/build.make CMakeFiles/__nuttx_patch_px4fmu-v2.dir/build
.PHONY : __nuttx_patch_px4fmu-v2/fast

#=============================================================================
# Target rules for targets named git_dspal

# Build rule for target.
git_dspal: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 git_dspal
.PHONY : git_dspal

# fast build rule for target.
git_dspal/fast:
	$(MAKE) -f CMakeFiles/git_dspal.dir/build.make CMakeFiles/git_dspal.dir/build
.PHONY : git_dspal/fast

#=============================================================================
# Target rules for targets named git_eigen

# Build rule for target.
git_eigen: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 git_eigen
.PHONY : git_eigen

# fast build rule for target.
git_eigen/fast:
	$(MAKE) -f CMakeFiles/git_eigen.dir/build.make CMakeFiles/git_eigen.dir/build
.PHONY : git_eigen/fast

#=============================================================================
# Target rules for targets named git_gencpp

# Build rule for target.
git_gencpp: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 git_gencpp
.PHONY : git_gencpp

# fast build rule for target.
git_gencpp/fast:
	$(MAKE) -f CMakeFiles/git_gencpp.dir/build.make CMakeFiles/git_gencpp.dir/build
.PHONY : git_gencpp/fast

#=============================================================================
# Target rules for targets named git_genmsg

# Build rule for target.
git_genmsg: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 git_genmsg
.PHONY : git_genmsg

# fast build rule for target.
git_genmsg/fast:
	$(MAKE) -f CMakeFiles/git_genmsg.dir/build.make CMakeFiles/git_genmsg.dir/build
.PHONY : git_genmsg/fast

#=============================================================================
# Target rules for targets named git_gtest

# Build rule for target.
git_gtest: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 git_gtest
.PHONY : git_gtest

# fast build rule for target.
git_gtest/fast:
	$(MAKE) -f CMakeFiles/git_gtest.dir/build.make CMakeFiles/git_gtest.dir/build
.PHONY : git_gtest/fast

#=============================================================================
# Target rules for targets named git_mavlink

# Build rule for target.
git_mavlink: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 git_mavlink
.PHONY : git_mavlink

# fast build rule for target.
git_mavlink/fast:
	$(MAKE) -f CMakeFiles/git_mavlink.dir/build.make CMakeFiles/git_mavlink.dir/build
.PHONY : git_mavlink/fast

#=============================================================================
# Target rules for targets named git_nuttx

# Build rule for target.
git_nuttx: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 git_nuttx
.PHONY : git_nuttx

# fast build rule for target.
git_nuttx/fast:
	$(MAKE) -f CMakeFiles/git_nuttx.dir/build.make CMakeFiles/git_nuttx.dir/build
.PHONY : git_nuttx/fast

#=============================================================================
# Target rules for targets named git_uavcan

# Build rule for target.
git_uavcan: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 git_uavcan
.PHONY : git_uavcan

# fast build rule for target.
git_uavcan/fast:
	$(MAKE) -f CMakeFiles/git_uavcan.dir/build.make CMakeFiles/git_uavcan.dir/build
.PHONY : git_uavcan/fast

#=============================================================================
# Target rules for targets named msg_gen

# Build rule for target.
msg_gen: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 msg_gen
.PHONY : msg_gen

# fast build rule for target.
msg_gen/fast:
	$(MAKE) -f CMakeFiles/msg_gen.dir/build.make CMakeFiles/msg_gen.dir/build
.PHONY : msg_gen/fast

#=============================================================================
# Target rules for targets named nuttx_export_px4fmu-v2

# Build rule for target.
nuttx_export_px4fmu-v2: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 nuttx_export_px4fmu-v2
.PHONY : nuttx_export_px4fmu-v2

# fast build rule for target.
nuttx_export_px4fmu-v2/fast:
	$(MAKE) -f CMakeFiles/nuttx_export_px4fmu-v2.dir/build.make CMakeFiles/nuttx_export_px4fmu-v2.dir/build
.PHONY : nuttx_export_px4fmu-v2/fast

#=============================================================================
# Target rules for targets named prebuild_targets

# Build rule for target.
prebuild_targets: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 prebuild_targets
.PHONY : prebuild_targets

# fast build rule for target.
prebuild_targets/fast:
	$(MAKE) -f CMakeFiles/prebuild_targets.dir/build.make CMakeFiles/prebuild_targets.dir/build
.PHONY : prebuild_targets/fast

#=============================================================================
# Target rules for targets named sercon

# Build rule for target.
sercon: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 sercon
.PHONY : sercon

# fast build rule for target.
sercon/fast:
	$(MAKE) -f CMakeFiles/sercon.dir/build.make CMakeFiles/sercon.dir/build
.PHONY : sercon/fast

#=============================================================================
# Target rules for targets named serdis

# Build rule for target.
serdis: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 serdis
.PHONY : serdis

# fast build rule for target.
serdis/fast:
	$(MAKE) -f CMakeFiles/serdis.dir/build.make CMakeFiles/serdis.dir/build
.PHONY : serdis/fast

#=============================================================================
# Target rules for targets named submodule_clean

# Build rule for target.
submodule_clean: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 submodule_clean
.PHONY : submodule_clean

# fast build rule for target.
submodule_clean/fast:
	$(MAKE) -f CMakeFiles/submodule_clean.dir/build.make CMakeFiles/submodule_clean.dir/build
.PHONY : submodule_clean/fast

#=============================================================================
# Target rules for targets named xml_gen

# Build rule for target.
xml_gen: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 xml_gen
.PHONY : xml_gen

# fast build rule for target.
xml_gen/fast:
	$(MAKE) -f CMakeFiles/xml_gen.dir/build.make CMakeFiles/xml_gen.dir/build
.PHONY : xml_gen/fast

#=============================================================================
# Target rules for targets named drivers__device

# Build rule for target.
drivers__device: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 drivers__device
.PHONY : drivers__device

# fast build rule for target.
drivers__device/fast:
	$(MAKE) -f src/drivers/device/CMakeFiles/drivers__device.dir/build.make src/drivers/device/CMakeFiles/drivers__device.dir/build
.PHONY : drivers__device/fast

#=============================================================================
# Target rules for targets named drivers__stm32

# Build rule for target.
drivers__stm32: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 drivers__stm32
.PHONY : drivers__stm32

# fast build rule for target.
drivers__stm32/fast:
	$(MAKE) -f src/drivers/stm32/CMakeFiles/drivers__stm32.dir/build.make src/drivers/stm32/CMakeFiles/drivers__stm32.dir/build
.PHONY : drivers__stm32/fast

#=============================================================================
# Target rules for targets named drivers__stm32__adc

# Build rule for target.
drivers__stm32__adc: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 drivers__stm32__adc
.PHONY : drivers__stm32__adc

# fast build rule for target.
drivers__stm32__adc/fast:
	$(MAKE) -f src/drivers/stm32/adc/CMakeFiles/drivers__stm32__adc.dir/build.make src/drivers/stm32/adc/CMakeFiles/drivers__stm32__adc.dir/build
.PHONY : drivers__stm32__adc/fast

#=============================================================================
# Target rules for targets named drivers__stm32__tone_alarm

# Build rule for target.
drivers__stm32__tone_alarm: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 drivers__stm32__tone_alarm
.PHONY : drivers__stm32__tone_alarm

# fast build rule for target.
drivers__stm32__tone_alarm/fast:
	$(MAKE) -f src/drivers/stm32/tone_alarm/CMakeFiles/drivers__stm32__tone_alarm.dir/build.make src/drivers/stm32/tone_alarm/CMakeFiles/drivers__stm32__tone_alarm.dir/build
.PHONY : drivers__stm32__tone_alarm/fast

#=============================================================================
# Target rules for targets named drivers__led

# Build rule for target.
drivers__led: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 drivers__led
.PHONY : drivers__led

# fast build rule for target.
drivers__led/fast:
	$(MAKE) -f src/drivers/led/CMakeFiles/drivers__led.dir/build.make src/drivers/led/CMakeFiles/drivers__led.dir/build
.PHONY : drivers__led/fast

#=============================================================================
# Target rules for targets named drivers__px4fmu

# Build rule for target.
drivers__px4fmu: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 drivers__px4fmu
.PHONY : drivers__px4fmu

# fast build rule for target.
drivers__px4fmu/fast:
	$(MAKE) -f src/drivers/px4fmu/CMakeFiles/drivers__px4fmu.dir/build.make src/drivers/px4fmu/CMakeFiles/drivers__px4fmu.dir/build
.PHONY : drivers__px4fmu/fast

#=============================================================================
# Target rules for targets named drivers__px4io

# Build rule for target.
drivers__px4io: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 drivers__px4io
.PHONY : drivers__px4io

# fast build rule for target.
drivers__px4io/fast:
	$(MAKE) -f src/drivers/px4io/CMakeFiles/drivers__px4io.dir/build.make src/drivers/px4io/CMakeFiles/drivers__px4io.dir/build
.PHONY : drivers__px4io/fast

#=============================================================================
# Target rules for targets named drivers__boards__px4fmu-v2

# Build rule for target.
drivers__boards__px4fmu-v2: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 drivers__boards__px4fmu-v2
.PHONY : drivers__boards__px4fmu-v2

# fast build rule for target.
drivers__boards__px4fmu-v2/fast:
	$(MAKE) -f src/drivers/boards/px4fmu-v2/CMakeFiles/drivers__boards__px4fmu-v2.dir/build.make src/drivers/boards/px4fmu-v2/CMakeFiles/drivers__boards__px4fmu-v2.dir/build
.PHONY : drivers__boards__px4fmu-v2/fast

#=============================================================================
# Target rules for targets named drivers__rgbled

# Build rule for target.
drivers__rgbled: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 drivers__rgbled
.PHONY : drivers__rgbled

# fast build rule for target.
drivers__rgbled/fast:
	$(MAKE) -f src/drivers/rgbled/CMakeFiles/drivers__rgbled.dir/build.make src/drivers/rgbled/CMakeFiles/drivers__rgbled.dir/build
.PHONY : drivers__rgbled/fast

#=============================================================================
# Target rules for targets named drivers__mpu6000

# Build rule for target.
drivers__mpu6000: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 drivers__mpu6000
.PHONY : drivers__mpu6000

# fast build rule for target.
drivers__mpu6000/fast:
	$(MAKE) -f src/drivers/mpu6000/CMakeFiles/drivers__mpu6000.dir/build.make src/drivers/mpu6000/CMakeFiles/drivers__mpu6000.dir/build
.PHONY : drivers__mpu6000/fast

#=============================================================================
# Target rules for targets named drivers__mpu9250

# Build rule for target.
drivers__mpu9250: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 drivers__mpu9250
.PHONY : drivers__mpu9250

# fast build rule for target.
drivers__mpu9250/fast:
	$(MAKE) -f src/drivers/mpu9250/CMakeFiles/drivers__mpu9250.dir/build.make src/drivers/mpu9250/CMakeFiles/drivers__mpu9250.dir/build
.PHONY : drivers__mpu9250/fast

#=============================================================================
# Target rules for targets named drivers__lsm303d

# Build rule for target.
drivers__lsm303d: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 drivers__lsm303d
.PHONY : drivers__lsm303d

# fast build rule for target.
drivers__lsm303d/fast:
	$(MAKE) -f src/drivers/lsm303d/CMakeFiles/drivers__lsm303d.dir/build.make src/drivers/lsm303d/CMakeFiles/drivers__lsm303d.dir/build
.PHONY : drivers__lsm303d/fast

#=============================================================================
# Target rules for targets named drivers__l3gd20

# Build rule for target.
drivers__l3gd20: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 drivers__l3gd20
.PHONY : drivers__l3gd20

# fast build rule for target.
drivers__l3gd20/fast:
	$(MAKE) -f src/drivers/l3gd20/CMakeFiles/drivers__l3gd20.dir/build.make src/drivers/l3gd20/CMakeFiles/drivers__l3gd20.dir/build
.PHONY : drivers__l3gd20/fast

#=============================================================================
# Target rules for targets named drivers__hmc5883

# Build rule for target.
drivers__hmc5883: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 drivers__hmc5883
.PHONY : drivers__hmc5883

# fast build rule for target.
drivers__hmc5883/fast:
	$(MAKE) -f src/drivers/hmc5883/CMakeFiles/drivers__hmc5883.dir/build.make src/drivers/hmc5883/CMakeFiles/drivers__hmc5883.dir/build
.PHONY : drivers__hmc5883/fast

#=============================================================================
# Target rules for targets named drivers__ms5611

# Build rule for target.
drivers__ms5611: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 drivers__ms5611
.PHONY : drivers__ms5611

# fast build rule for target.
drivers__ms5611/fast:
	$(MAKE) -f src/drivers/ms5611/CMakeFiles/drivers__ms5611.dir/build.make src/drivers/ms5611/CMakeFiles/drivers__ms5611.dir/build
.PHONY : drivers__ms5611/fast

#=============================================================================
# Target rules for targets named drivers__mb12xx

# Build rule for target.
drivers__mb12xx: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 drivers__mb12xx
.PHONY : drivers__mb12xx

# fast build rule for target.
drivers__mb12xx/fast:
	$(MAKE) -f src/drivers/mb12xx/CMakeFiles/drivers__mb12xx.dir/build.make src/drivers/mb12xx/CMakeFiles/drivers__mb12xx.dir/build
.PHONY : drivers__mb12xx/fast

#=============================================================================
# Target rules for targets named drivers__sf0x

# Build rule for target.
drivers__sf0x: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 drivers__sf0x
.PHONY : drivers__sf0x

# fast build rule for target.
drivers__sf0x/fast:
	$(MAKE) -f src/drivers/sf0x/CMakeFiles/drivers__sf0x.dir/build.make src/drivers/sf0x/CMakeFiles/drivers__sf0x.dir/build
.PHONY : drivers__sf0x/fast

#=============================================================================
# Target rules for targets named drivers__ll40ls

# Build rule for target.
drivers__ll40ls: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 drivers__ll40ls
.PHONY : drivers__ll40ls

# fast build rule for target.
drivers__ll40ls/fast:
	$(MAKE) -f src/drivers/ll40ls/CMakeFiles/drivers__ll40ls.dir/build.make src/drivers/ll40ls/CMakeFiles/drivers__ll40ls.dir/build
.PHONY : drivers__ll40ls/fast

#=============================================================================
# Target rules for targets named drivers__trone

# Build rule for target.
drivers__trone: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 drivers__trone
.PHONY : drivers__trone

# fast build rule for target.
drivers__trone/fast:
	$(MAKE) -f src/drivers/trone/CMakeFiles/drivers__trone.dir/build.make src/drivers/trone/CMakeFiles/drivers__trone.dir/build
.PHONY : drivers__trone/fast

#=============================================================================
# Target rules for targets named drivers__gps

# Build rule for target.
drivers__gps: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 drivers__gps
.PHONY : drivers__gps

# fast build rule for target.
drivers__gps/fast:
	$(MAKE) -f src/drivers/gps/CMakeFiles/drivers__gps.dir/build.make src/drivers/gps/CMakeFiles/drivers__gps.dir/build
.PHONY : drivers__gps/fast

#=============================================================================
# Target rules for targets named drivers__pwm_out_sim

# Build rule for target.
drivers__pwm_out_sim: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 drivers__pwm_out_sim
.PHONY : drivers__pwm_out_sim

# fast build rule for target.
drivers__pwm_out_sim/fast:
	$(MAKE) -f src/drivers/pwm_out_sim/CMakeFiles/drivers__pwm_out_sim.dir/build.make src/drivers/pwm_out_sim/CMakeFiles/drivers__pwm_out_sim.dir/build
.PHONY : drivers__pwm_out_sim/fast

#=============================================================================
# Target rules for targets named drivers__hott

# Build rule for target.
drivers__hott: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 drivers__hott
.PHONY : drivers__hott

# fast build rule for target.
drivers__hott/fast:
	$(MAKE) -f src/drivers/hott/CMakeFiles/drivers__hott.dir/build.make src/drivers/hott/CMakeFiles/drivers__hott.dir/build
.PHONY : drivers__hott/fast

#=============================================================================
# Target rules for targets named drivers__hott__hott_telemetry

# Build rule for target.
drivers__hott__hott_telemetry: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 drivers__hott__hott_telemetry
.PHONY : drivers__hott__hott_telemetry

# fast build rule for target.
drivers__hott__hott_telemetry/fast:
	$(MAKE) -f src/drivers/hott/hott_telemetry/CMakeFiles/drivers__hott__hott_telemetry.dir/build.make src/drivers/hott/hott_telemetry/CMakeFiles/drivers__hott__hott_telemetry.dir/build
.PHONY : drivers__hott__hott_telemetry/fast

#=============================================================================
# Target rules for targets named drivers__hott__hott_sensors

# Build rule for target.
drivers__hott__hott_sensors: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 drivers__hott__hott_sensors
.PHONY : drivers__hott__hott_sensors

# fast build rule for target.
drivers__hott__hott_sensors/fast:
	$(MAKE) -f src/drivers/hott/hott_sensors/CMakeFiles/drivers__hott__hott_sensors.dir/build.make src/drivers/hott/hott_sensors/CMakeFiles/drivers__hott__hott_sensors.dir/build
.PHONY : drivers__hott__hott_sensors/fast

#=============================================================================
# Target rules for targets named drivers__blinkm

# Build rule for target.
drivers__blinkm: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 drivers__blinkm
.PHONY : drivers__blinkm

# fast build rule for target.
drivers__blinkm/fast:
	$(MAKE) -f src/drivers/blinkm/CMakeFiles/drivers__blinkm.dir/build.make src/drivers/blinkm/CMakeFiles/drivers__blinkm.dir/build
.PHONY : drivers__blinkm/fast

#=============================================================================
# Target rules for targets named drivers__airspeed

# Build rule for target.
drivers__airspeed: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 drivers__airspeed
.PHONY : drivers__airspeed

# fast build rule for target.
drivers__airspeed/fast:
	$(MAKE) -f src/drivers/airspeed/CMakeFiles/drivers__airspeed.dir/build.make src/drivers/airspeed/CMakeFiles/drivers__airspeed.dir/build
.PHONY : drivers__airspeed/fast

#=============================================================================
# Target rules for targets named drivers__ets_airspeed

# Build rule for target.
drivers__ets_airspeed: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 drivers__ets_airspeed
.PHONY : drivers__ets_airspeed

# fast build rule for target.
drivers__ets_airspeed/fast:
	$(MAKE) -f src/drivers/ets_airspeed/CMakeFiles/drivers__ets_airspeed.dir/build.make src/drivers/ets_airspeed/CMakeFiles/drivers__ets_airspeed.dir/build
.PHONY : drivers__ets_airspeed/fast

#=============================================================================
# Target rules for targets named drivers__meas_airspeed

# Build rule for target.
drivers__meas_airspeed: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 drivers__meas_airspeed
.PHONY : drivers__meas_airspeed

# fast build rule for target.
drivers__meas_airspeed/fast:
	$(MAKE) -f src/drivers/meas_airspeed/CMakeFiles/drivers__meas_airspeed.dir/build.make src/drivers/meas_airspeed/CMakeFiles/drivers__meas_airspeed.dir/build
.PHONY : drivers__meas_airspeed/fast

#=============================================================================
# Target rules for targets named drivers__frsky_telemetry

# Build rule for target.
drivers__frsky_telemetry: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 drivers__frsky_telemetry
.PHONY : drivers__frsky_telemetry

# fast build rule for target.
drivers__frsky_telemetry/fast:
	$(MAKE) -f src/drivers/frsky_telemetry/CMakeFiles/drivers__frsky_telemetry.dir/build.make src/drivers/frsky_telemetry/CMakeFiles/drivers__frsky_telemetry.dir/build
.PHONY : drivers__frsky_telemetry/fast

#=============================================================================
# Target rules for targets named modules__sensors

# Build rule for target.
modules__sensors: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 modules__sensors
.PHONY : modules__sensors

# fast build rule for target.
modules__sensors/fast:
	$(MAKE) -f src/modules/sensors/CMakeFiles/modules__sensors.dir/build.make src/modules/sensors/CMakeFiles/modules__sensors.dir/build
.PHONY : modules__sensors/fast

#=============================================================================
# Target rules for targets named drivers__mkblctrl

# Build rule for target.
drivers__mkblctrl: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 drivers__mkblctrl
.PHONY : drivers__mkblctrl

# fast build rule for target.
drivers__mkblctrl/fast:
	$(MAKE) -f src/drivers/mkblctrl/CMakeFiles/drivers__mkblctrl.dir/build.make src/drivers/mkblctrl/CMakeFiles/drivers__mkblctrl.dir/build
.PHONY : drivers__mkblctrl/fast

#=============================================================================
# Target rules for targets named drivers__px4flow

# Build rule for target.
drivers__px4flow: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 drivers__px4flow
.PHONY : drivers__px4flow

# fast build rule for target.
drivers__px4flow/fast:
	$(MAKE) -f src/drivers/px4flow/CMakeFiles/drivers__px4flow.dir/build.make src/drivers/px4flow/CMakeFiles/drivers__px4flow.dir/build
.PHONY : drivers__px4flow/fast

#=============================================================================
# Target rules for targets named drivers__oreoled

# Build rule for target.
drivers__oreoled: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 drivers__oreoled
.PHONY : drivers__oreoled

# fast build rule for target.
drivers__oreoled/fast:
	$(MAKE) -f src/drivers/oreoled/CMakeFiles/drivers__oreoled.dir/build.make src/drivers/oreoled/CMakeFiles/drivers__oreoled.dir/build
.PHONY : drivers__oreoled/fast

#=============================================================================
# Target rules for targets named drivers__gimbal

# Build rule for target.
drivers__gimbal: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 drivers__gimbal
.PHONY : drivers__gimbal

# fast build rule for target.
drivers__gimbal/fast:
	$(MAKE) -f src/drivers/gimbal/CMakeFiles/drivers__gimbal.dir/build.make src/drivers/gimbal/CMakeFiles/drivers__gimbal.dir/build
.PHONY : drivers__gimbal/fast

#=============================================================================
# Target rules for targets named drivers__pwm_input

# Build rule for target.
drivers__pwm_input: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 drivers__pwm_input
.PHONY : drivers__pwm_input

# fast build rule for target.
drivers__pwm_input/fast:
	$(MAKE) -f src/drivers/pwm_input/CMakeFiles/drivers__pwm_input.dir/build.make src/drivers/pwm_input/CMakeFiles/drivers__pwm_input.dir/build
.PHONY : drivers__pwm_input/fast

#=============================================================================
# Target rules for targets named drivers__camera_trigger

# Build rule for target.
drivers__camera_trigger: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 drivers__camera_trigger
.PHONY : drivers__camera_trigger

# fast build rule for target.
drivers__camera_trigger/fast:
	$(MAKE) -f src/drivers/camera_trigger/CMakeFiles/drivers__camera_trigger.dir/build.make src/drivers/camera_trigger/CMakeFiles/drivers__camera_trigger.dir/build
.PHONY : drivers__camera_trigger/fast

#=============================================================================
# Target rules for targets named systemcmds__bl_update

# Build rule for target.
systemcmds__bl_update: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 systemcmds__bl_update
.PHONY : systemcmds__bl_update

# fast build rule for target.
systemcmds__bl_update/fast:
	$(MAKE) -f src/systemcmds/bl_update/CMakeFiles/systemcmds__bl_update.dir/build.make src/systemcmds/bl_update/CMakeFiles/systemcmds__bl_update.dir/build
.PHONY : systemcmds__bl_update/fast

#=============================================================================
# Target rules for targets named systemcmds__mixer

# Build rule for target.
systemcmds__mixer: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 systemcmds__mixer
.PHONY : systemcmds__mixer

# fast build rule for target.
systemcmds__mixer/fast:
	$(MAKE) -f src/systemcmds/mixer/CMakeFiles/systemcmds__mixer.dir/build.make src/systemcmds/mixer/CMakeFiles/systemcmds__mixer.dir/build
.PHONY : systemcmds__mixer/fast

#=============================================================================
# Target rules for targets named systemcmds__param

# Build rule for target.
systemcmds__param: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 systemcmds__param
.PHONY : systemcmds__param

# fast build rule for target.
systemcmds__param/fast:
	$(MAKE) -f src/systemcmds/param/CMakeFiles/systemcmds__param.dir/build.make src/systemcmds/param/CMakeFiles/systemcmds__param.dir/build
.PHONY : systemcmds__param/fast

#=============================================================================
# Target rules for targets named systemcmds__perf

# Build rule for target.
systemcmds__perf: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 systemcmds__perf
.PHONY : systemcmds__perf

# fast build rule for target.
systemcmds__perf/fast:
	$(MAKE) -f src/systemcmds/perf/CMakeFiles/systemcmds__perf.dir/build.make src/systemcmds/perf/CMakeFiles/systemcmds__perf.dir/build
.PHONY : systemcmds__perf/fast

#=============================================================================
# Target rules for targets named systemcmds__pwm

# Build rule for target.
systemcmds__pwm: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 systemcmds__pwm
.PHONY : systemcmds__pwm

# fast build rule for target.
systemcmds__pwm/fast:
	$(MAKE) -f src/systemcmds/pwm/CMakeFiles/systemcmds__pwm.dir/build.make src/systemcmds/pwm/CMakeFiles/systemcmds__pwm.dir/build
.PHONY : systemcmds__pwm/fast

#=============================================================================
# Target rules for targets named systemcmds__esc_calib

# Build rule for target.
systemcmds__esc_calib: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 systemcmds__esc_calib
.PHONY : systemcmds__esc_calib

# fast build rule for target.
systemcmds__esc_calib/fast:
	$(MAKE) -f src/systemcmds/esc_calib/CMakeFiles/systemcmds__esc_calib.dir/build.make src/systemcmds/esc_calib/CMakeFiles/systemcmds__esc_calib.dir/build
.PHONY : systemcmds__esc_calib/fast

#=============================================================================
# Target rules for targets named systemcmds__reboot

# Build rule for target.
systemcmds__reboot: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 systemcmds__reboot
.PHONY : systemcmds__reboot

# fast build rule for target.
systemcmds__reboot/fast:
	$(MAKE) -f src/systemcmds/reboot/CMakeFiles/systemcmds__reboot.dir/build.make src/systemcmds/reboot/CMakeFiles/systemcmds__reboot.dir/build
.PHONY : systemcmds__reboot/fast

#=============================================================================
# Target rules for targets named generate_topic_listener

# Build rule for target.
generate_topic_listener: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 generate_topic_listener
.PHONY : generate_topic_listener

# fast build rule for target.
generate_topic_listener/fast:
	$(MAKE) -f src/systemcmds/topic_listener/CMakeFiles/generate_topic_listener.dir/build.make src/systemcmds/topic_listener/CMakeFiles/generate_topic_listener.dir/build
.PHONY : generate_topic_listener/fast

#=============================================================================
# Target rules for targets named systemcmds__topic_listener

# Build rule for target.
systemcmds__topic_listener: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 systemcmds__topic_listener
.PHONY : systemcmds__topic_listener

# fast build rule for target.
systemcmds__topic_listener/fast:
	$(MAKE) -f src/systemcmds/topic_listener/CMakeFiles/systemcmds__topic_listener.dir/build.make src/systemcmds/topic_listener/CMakeFiles/systemcmds__topic_listener.dir/build
.PHONY : systemcmds__topic_listener/fast

#=============================================================================
# Target rules for targets named systemcmds__top

# Build rule for target.
systemcmds__top: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 systemcmds__top
.PHONY : systemcmds__top

# fast build rule for target.
systemcmds__top/fast:
	$(MAKE) -f src/systemcmds/top/CMakeFiles/systemcmds__top.dir/build.make src/systemcmds/top/CMakeFiles/systemcmds__top.dir/build
.PHONY : systemcmds__top/fast

#=============================================================================
# Target rules for targets named systemcmds__config

# Build rule for target.
systemcmds__config: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 systemcmds__config
.PHONY : systemcmds__config

# fast build rule for target.
systemcmds__config/fast:
	$(MAKE) -f src/systemcmds/config/CMakeFiles/systemcmds__config.dir/build.make src/systemcmds/config/CMakeFiles/systemcmds__config.dir/build
.PHONY : systemcmds__config/fast

#=============================================================================
# Target rules for targets named systemcmds__nshterm

# Build rule for target.
systemcmds__nshterm: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 systemcmds__nshterm
.PHONY : systemcmds__nshterm

# fast build rule for target.
systemcmds__nshterm/fast:
	$(MAKE) -f src/systemcmds/nshterm/CMakeFiles/systemcmds__nshterm.dir/build.make src/systemcmds/nshterm/CMakeFiles/systemcmds__nshterm.dir/build
.PHONY : systemcmds__nshterm/fast

#=============================================================================
# Target rules for targets named systemcmds__mtd

# Build rule for target.
systemcmds__mtd: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 systemcmds__mtd
.PHONY : systemcmds__mtd

# fast build rule for target.
systemcmds__mtd/fast:
	$(MAKE) -f src/systemcmds/mtd/CMakeFiles/systemcmds__mtd.dir/build.make src/systemcmds/mtd/CMakeFiles/systemcmds__mtd.dir/build
.PHONY : systemcmds__mtd/fast

#=============================================================================
# Target rules for targets named systemcmds__dumpfile

# Build rule for target.
systemcmds__dumpfile: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 systemcmds__dumpfile
.PHONY : systemcmds__dumpfile

# fast build rule for target.
systemcmds__dumpfile/fast:
	$(MAKE) -f src/systemcmds/dumpfile/CMakeFiles/systemcmds__dumpfile.dir/build.make src/systemcmds/dumpfile/CMakeFiles/systemcmds__dumpfile.dir/build
.PHONY : systemcmds__dumpfile/fast

#=============================================================================
# Target rules for targets named systemcmds__ver

# Build rule for target.
systemcmds__ver: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 systemcmds__ver
.PHONY : systemcmds__ver

# fast build rule for target.
systemcmds__ver/fast:
	$(MAKE) -f src/systemcmds/ver/CMakeFiles/systemcmds__ver.dir/build.make src/systemcmds/ver/CMakeFiles/systemcmds__ver.dir/build
.PHONY : systemcmds__ver/fast

#=============================================================================
# Target rules for targets named modules__commander

# Build rule for target.
modules__commander: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 modules__commander
.PHONY : modules__commander

# fast build rule for target.
modules__commander/fast:
	$(MAKE) -f src/modules/commander/CMakeFiles/modules__commander.dir/build.make src/modules/commander/CMakeFiles/modules__commander.dir/build
.PHONY : modules__commander/fast

#=============================================================================
# Target rules for targets named modules__navigator

# Build rule for target.
modules__navigator: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 modules__navigator
.PHONY : modules__navigator

# fast build rule for target.
modules__navigator/fast:
	$(MAKE) -f src/modules/navigator/CMakeFiles/modules__navigator.dir/build.make src/modules/navigator/CMakeFiles/modules__navigator.dir/build
.PHONY : modules__navigator/fast

#=============================================================================
# Target rules for targets named modules__mavlink

# Build rule for target.
modules__mavlink: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 modules__mavlink
.PHONY : modules__mavlink

# fast build rule for target.
modules__mavlink/fast:
	$(MAKE) -f src/modules/mavlink/CMakeFiles/modules__mavlink.dir/build.make src/modules/mavlink/CMakeFiles/modules__mavlink.dir/build
.PHONY : modules__mavlink/fast

#=============================================================================
# Target rules for targets named modules__gpio_led

# Build rule for target.
modules__gpio_led: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 modules__gpio_led
.PHONY : modules__gpio_led

# fast build rule for target.
modules__gpio_led/fast:
	$(MAKE) -f src/modules/gpio_led/CMakeFiles/modules__gpio_led.dir/build.make src/modules/gpio_led/CMakeFiles/modules__gpio_led.dir/build
.PHONY : modules__gpio_led/fast

#=============================================================================
# Target rules for targets named modules__uavcan

# Build rule for target.
modules__uavcan: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 modules__uavcan
.PHONY : modules__uavcan

# fast build rule for target.
modules__uavcan/fast:
	$(MAKE) -f src/modules/uavcan/CMakeFiles/modules__uavcan.dir/build.make src/modules/uavcan/CMakeFiles/modules__uavcan.dir/build
.PHONY : modules__uavcan/fast

#=============================================================================
# Target rules for targets named libuavcan_dsdlc

# Build rule for target.
libuavcan_dsdlc: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 libuavcan_dsdlc
.PHONY : libuavcan_dsdlc

# fast build rule for target.
libuavcan_dsdlc/fast:
	$(MAKE) -f src/modules/uavcan/libuavcan/libuavcan/CMakeFiles/libuavcan_dsdlc.dir/build.make src/modules/uavcan/libuavcan/libuavcan/CMakeFiles/libuavcan_dsdlc.dir/build
.PHONY : libuavcan_dsdlc/fast

#=============================================================================
# Target rules for targets named uavcan

# Build rule for target.
uavcan: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 uavcan
.PHONY : uavcan

# fast build rule for target.
uavcan/fast:
	$(MAKE) -f src/modules/uavcan/libuavcan/libuavcan/CMakeFiles/uavcan.dir/build.make src/modules/uavcan/libuavcan/libuavcan/CMakeFiles/uavcan.dir/build
.PHONY : uavcan/fast

#=============================================================================
# Target rules for targets named uavcan_stm32_driver

# Build rule for target.
uavcan_stm32_driver: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 uavcan_stm32_driver
.PHONY : uavcan_stm32_driver

# fast build rule for target.
uavcan_stm32_driver/fast:
	$(MAKE) -f src/modules/uavcan/libuavcan/libuavcan_drivers/stm32/driver/CMakeFiles/uavcan_stm32_driver.dir/build.make src/modules/uavcan/libuavcan/libuavcan_drivers/stm32/driver/CMakeFiles/uavcan_stm32_driver.dir/build
.PHONY : uavcan_stm32_driver/fast

#=============================================================================
# Target rules for targets named modules__land_detector

# Build rule for target.
modules__land_detector: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 modules__land_detector
.PHONY : modules__land_detector

# fast build rule for target.
modules__land_detector/fast:
	$(MAKE) -f src/modules/land_detector/CMakeFiles/modules__land_detector.dir/build.make src/modules/land_detector/CMakeFiles/modules__land_detector.dir/build
.PHONY : modules__land_detector/fast

#=============================================================================
# Target rules for targets named modules__attitude_estimator_q

# Build rule for target.
modules__attitude_estimator_q: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 modules__attitude_estimator_q
.PHONY : modules__attitude_estimator_q

# fast build rule for target.
modules__attitude_estimator_q/fast:
	$(MAKE) -f src/modules/attitude_estimator_q/CMakeFiles/modules__attitude_estimator_q.dir/build.make src/modules/attitude_estimator_q/CMakeFiles/modules__attitude_estimator_q.dir/build
.PHONY : modules__attitude_estimator_q/fast

#=============================================================================
# Target rules for targets named modules__ekf_att_pos_estimator

# Build rule for target.
modules__ekf_att_pos_estimator: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 modules__ekf_att_pos_estimator
.PHONY : modules__ekf_att_pos_estimator

# fast build rule for target.
modules__ekf_att_pos_estimator/fast:
	$(MAKE) -f src/modules/ekf_att_pos_estimator/CMakeFiles/modules__ekf_att_pos_estimator.dir/build.make src/modules/ekf_att_pos_estimator/CMakeFiles/modules__ekf_att_pos_estimator.dir/build
.PHONY : modules__ekf_att_pos_estimator/fast

#=============================================================================
# Target rules for targets named modules__position_estimator_inav

# Build rule for target.
modules__position_estimator_inav: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 modules__position_estimator_inav
.PHONY : modules__position_estimator_inav

# fast build rule for target.
modules__position_estimator_inav/fast:
	$(MAKE) -f src/modules/position_estimator_inav/CMakeFiles/modules__position_estimator_inav.dir/build.make src/modules/position_estimator_inav/CMakeFiles/modules__position_estimator_inav.dir/build
.PHONY : modules__position_estimator_inav/fast

#=============================================================================
# Target rules for targets named modules__anfis_att_control

# Build rule for target.
modules__anfis_att_control: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 modules__anfis_att_control
.PHONY : modules__anfis_att_control

# fast build rule for target.
modules__anfis_att_control/fast:
	$(MAKE) -f src/modules/anfis_att_control/CMakeFiles/modules__anfis_att_control.dir/build.make src/modules/anfis_att_control/CMakeFiles/modules__anfis_att_control.dir/build
.PHONY : modules__anfis_att_control/fast

#=============================================================================
# Target rules for targets named modules__fw_pos_control_l1

# Build rule for target.
modules__fw_pos_control_l1: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 modules__fw_pos_control_l1
.PHONY : modules__fw_pos_control_l1

# fast build rule for target.
modules__fw_pos_control_l1/fast:
	$(MAKE) -f src/modules/fw_pos_control_l1/CMakeFiles/modules__fw_pos_control_l1.dir/build.make src/modules/fw_pos_control_l1/CMakeFiles/modules__fw_pos_control_l1.dir/build
.PHONY : modules__fw_pos_control_l1/fast

#=============================================================================
# Target rules for targets named modules__fw_att_control

# Build rule for target.
modules__fw_att_control: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 modules__fw_att_control
.PHONY : modules__fw_att_control

# fast build rule for target.
modules__fw_att_control/fast:
	$(MAKE) -f src/modules/fw_att_control/CMakeFiles/modules__fw_att_control.dir/build.make src/modules/fw_att_control/CMakeFiles/modules__fw_att_control.dir/build
.PHONY : modules__fw_att_control/fast

#=============================================================================
# Target rules for targets named modules__mc_att_control

# Build rule for target.
modules__mc_att_control: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 modules__mc_att_control
.PHONY : modules__mc_att_control

# fast build rule for target.
modules__mc_att_control/fast:
	$(MAKE) -f src/modules/mc_att_control/CMakeFiles/modules__mc_att_control.dir/build.make src/modules/mc_att_control/CMakeFiles/modules__mc_att_control.dir/build
.PHONY : modules__mc_att_control/fast

#=============================================================================
# Target rules for targets named modules__mc_pos_control

# Build rule for target.
modules__mc_pos_control: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 modules__mc_pos_control
.PHONY : modules__mc_pos_control

# fast build rule for target.
modules__mc_pos_control/fast:
	$(MAKE) -f src/modules/mc_pos_control/CMakeFiles/modules__mc_pos_control.dir/build.make src/modules/mc_pos_control/CMakeFiles/modules__mc_pos_control.dir/build
.PHONY : modules__mc_pos_control/fast

#=============================================================================
# Target rules for targets named modules__vtol_att_control

# Build rule for target.
modules__vtol_att_control: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 modules__vtol_att_control
.PHONY : modules__vtol_att_control

# fast build rule for target.
modules__vtol_att_control/fast:
	$(MAKE) -f src/modules/vtol_att_control/CMakeFiles/modules__vtol_att_control.dir/build.make src/modules/vtol_att_control/CMakeFiles/modules__vtol_att_control.dir/build
.PHONY : modules__vtol_att_control/fast

#=============================================================================
# Target rules for targets named modules__sdlog2

# Build rule for target.
modules__sdlog2: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 modules__sdlog2
.PHONY : modules__sdlog2

# fast build rule for target.
modules__sdlog2/fast:
	$(MAKE) -f src/modules/sdlog2/CMakeFiles/modules__sdlog2.dir/build.make src/modules/sdlog2/CMakeFiles/modules__sdlog2.dir/build
.PHONY : modules__sdlog2/fast

#=============================================================================
# Target rules for targets named modules__param

# Build rule for target.
modules__param: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 modules__param
.PHONY : modules__param

# fast build rule for target.
modules__param/fast:
	$(MAKE) -f src/modules/param/CMakeFiles/modules__param.dir/build.make src/modules/param/CMakeFiles/modules__param.dir/build
.PHONY : modules__param/fast

#=============================================================================
# Target rules for targets named modules__systemlib

# Build rule for target.
modules__systemlib: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 modules__systemlib
.PHONY : modules__systemlib

# fast build rule for target.
modules__systemlib/fast:
	$(MAKE) -f src/modules/systemlib/CMakeFiles/modules__systemlib.dir/build.make src/modules/systemlib/CMakeFiles/modules__systemlib.dir/build
.PHONY : modules__systemlib/fast

#=============================================================================
# Target rules for targets named mixer_gen

# Build rule for target.
mixer_gen: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 mixer_gen
.PHONY : mixer_gen

# fast build rule for target.
mixer_gen/fast:
	$(MAKE) -f src/modules/systemlib/mixer/CMakeFiles/mixer_gen.dir/build.make src/modules/systemlib/mixer/CMakeFiles/mixer_gen.dir/build
.PHONY : mixer_gen/fast

#=============================================================================
# Target rules for targets named modules__systemlib__mixer

# Build rule for target.
modules__systemlib__mixer: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 modules__systemlib__mixer
.PHONY : modules__systemlib__mixer

# fast build rule for target.
modules__systemlib__mixer/fast:
	$(MAKE) -f src/modules/systemlib/mixer/CMakeFiles/modules__systemlib__mixer.dir/build.make src/modules/systemlib/mixer/CMakeFiles/modules__systemlib__mixer.dir/build
.PHONY : modules__systemlib__mixer/fast

#=============================================================================
# Target rules for targets named modules__controllib

# Build rule for target.
modules__controllib: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 modules__controllib
.PHONY : modules__controllib

# fast build rule for target.
modules__controllib/fast:
	$(MAKE) -f src/modules/controllib/CMakeFiles/modules__controllib.dir/build.make src/modules/controllib/CMakeFiles/modules__controllib.dir/build
.PHONY : modules__controllib/fast

#=============================================================================
# Target rules for targets named modules__uORB

# Build rule for target.
modules__uORB: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 modules__uORB
.PHONY : modules__uORB

# fast build rule for target.
modules__uORB/fast:
	$(MAKE) -f src/modules/uORB/CMakeFiles/modules__uORB.dir/build.make src/modules/uORB/CMakeFiles/modules__uORB.dir/build
.PHONY : modules__uORB/fast

#=============================================================================
# Target rules for targets named modules__dataman

# Build rule for target.
modules__dataman: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 modules__dataman
.PHONY : modules__dataman

# fast build rule for target.
modules__dataman/fast:
	$(MAKE) -f src/modules/dataman/CMakeFiles/modules__dataman.dir/build.make src/modules/dataman/CMakeFiles/modules__dataman.dir/build
.PHONY : modules__dataman/fast

#=============================================================================
# Target rules for targets named lib__mathlib

# Build rule for target.
lib__mathlib: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 lib__mathlib
.PHONY : lib__mathlib

# fast build rule for target.
lib__mathlib/fast:
	$(MAKE) -f src/lib/mathlib/CMakeFiles/lib__mathlib.dir/build.make src/lib/mathlib/CMakeFiles/lib__mathlib.dir/build
.PHONY : lib__mathlib/fast

#=============================================================================
# Target rules for targets named lib__mathlib__math__filter

# Build rule for target.
lib__mathlib__math__filter: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 lib__mathlib__math__filter
.PHONY : lib__mathlib__math__filter

# fast build rule for target.
lib__mathlib__math__filter/fast:
	$(MAKE) -f src/lib/mathlib/math/filter/CMakeFiles/lib__mathlib__math__filter.dir/build.make src/lib/mathlib/math/filter/CMakeFiles/lib__mathlib__math__filter.dir/build
.PHONY : lib__mathlib__math__filter/fast

#=============================================================================
# Target rules for targets named lib__ecl

# Build rule for target.
lib__ecl: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 lib__ecl
.PHONY : lib__ecl

# fast build rule for target.
lib__ecl/fast:
	$(MAKE) -f src/lib/ecl/CMakeFiles/lib__ecl.dir/build.make src/lib/ecl/CMakeFiles/lib__ecl.dir/build
.PHONY : lib__ecl/fast

#=============================================================================
# Target rules for targets named lib__external_lgpl

# Build rule for target.
lib__external_lgpl: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 lib__external_lgpl
.PHONY : lib__external_lgpl

# fast build rule for target.
lib__external_lgpl/fast:
	$(MAKE) -f src/lib/external_lgpl/CMakeFiles/lib__external_lgpl.dir/build.make src/lib/external_lgpl/CMakeFiles/lib__external_lgpl.dir/build
.PHONY : lib__external_lgpl/fast

#=============================================================================
# Target rules for targets named lib__geo

# Build rule for target.
lib__geo: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 lib__geo
.PHONY : lib__geo

# fast build rule for target.
lib__geo/fast:
	$(MAKE) -f src/lib/geo/CMakeFiles/lib__geo.dir/build.make src/lib/geo/CMakeFiles/lib__geo.dir/build
.PHONY : lib__geo/fast

#=============================================================================
# Target rules for targets named lib__geo_lookup

# Build rule for target.
lib__geo_lookup: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 lib__geo_lookup
.PHONY : lib__geo_lookup

# fast build rule for target.
lib__geo_lookup/fast:
	$(MAKE) -f src/lib/geo_lookup/CMakeFiles/lib__geo_lookup.dir/build.make src/lib/geo_lookup/CMakeFiles/lib__geo_lookup.dir/build
.PHONY : lib__geo_lookup/fast

#=============================================================================
# Target rules for targets named lib__conversion

# Build rule for target.
lib__conversion: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 lib__conversion
.PHONY : lib__conversion

# fast build rule for target.
lib__conversion/fast:
	$(MAKE) -f src/lib/conversion/CMakeFiles/lib__conversion.dir/build.make src/lib/conversion/CMakeFiles/lib__conversion.dir/build
.PHONY : lib__conversion/fast

#=============================================================================
# Target rules for targets named lib__launchdetection

# Build rule for target.
lib__launchdetection: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 lib__launchdetection
.PHONY : lib__launchdetection

# fast build rule for target.
lib__launchdetection/fast:
	$(MAKE) -f src/lib/launchdetection/CMakeFiles/lib__launchdetection.dir/build.make src/lib/launchdetection/CMakeFiles/lib__launchdetection.dir/build
.PHONY : lib__launchdetection/fast

#=============================================================================
# Target rules for targets named platforms__nuttx

# Build rule for target.
platforms__nuttx: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 platforms__nuttx
.PHONY : platforms__nuttx

# fast build rule for target.
platforms__nuttx/fast:
	$(MAKE) -f src/platforms/nuttx/CMakeFiles/platforms__nuttx.dir/build.make src/platforms/nuttx/CMakeFiles/platforms__nuttx.dir/build
.PHONY : platforms__nuttx/fast

#=============================================================================
# Target rules for targets named platforms__common

# Build rule for target.
platforms__common: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 platforms__common
.PHONY : platforms__common

# fast build rule for target.
platforms__common/fast:
	$(MAKE) -f src/platforms/common/CMakeFiles/platforms__common.dir/build.make src/platforms/common/CMakeFiles/platforms__common.dir/build
.PHONY : platforms__common/fast

#=============================================================================
# Target rules for targets named platforms__nuttx__px4_layer

# Build rule for target.
platforms__nuttx__px4_layer: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 platforms__nuttx__px4_layer
.PHONY : platforms__nuttx__px4_layer

# fast build rule for target.
platforms__nuttx__px4_layer/fast:
	$(MAKE) -f src/platforms/nuttx/px4_layer/CMakeFiles/platforms__nuttx__px4_layer.dir/build.make src/platforms/nuttx/px4_layer/CMakeFiles/platforms__nuttx__px4_layer.dir/build
.PHONY : platforms__nuttx__px4_layer/fast

#=============================================================================
# Target rules for targets named modules__bottle_drop

# Build rule for target.
modules__bottle_drop: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 modules__bottle_drop
.PHONY : modules__bottle_drop

# fast build rule for target.
modules__bottle_drop/fast:
	$(MAKE) -f src/modules/bottle_drop/CMakeFiles/modules__bottle_drop.dir/build.make src/modules/bottle_drop/CMakeFiles/modules__bottle_drop.dir/build
.PHONY : modules__bottle_drop/fast

#=============================================================================
# Target rules for targets named examples__rover_steering_control

# Build rule for target.
examples__rover_steering_control: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 examples__rover_steering_control
.PHONY : examples__rover_steering_control

# fast build rule for target.
examples__rover_steering_control/fast:
	$(MAKE) -f src/examples/rover_steering_control/CMakeFiles/examples__rover_steering_control.dir/build.make src/examples/rover_steering_control/CMakeFiles/examples__rover_steering_control.dir/build
.PHONY : examples__rover_steering_control/fast

#=============================================================================
# Target rules for targets named build_firmware_px4fmu-v2

# Build rule for target.
build_firmware_px4fmu-v2: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 build_firmware_px4fmu-v2
.PHONY : build_firmware_px4fmu-v2

# fast build rule for target.
build_firmware_px4fmu-v2/fast:
	$(MAKE) -f src/firmware/nuttx/CMakeFiles/build_firmware_px4fmu-v2.dir/build.make src/firmware/nuttx/CMakeFiles/build_firmware_px4fmu-v2.dir/build
.PHONY : build_firmware_px4fmu-v2/fast

#=============================================================================
# Target rules for targets named check_weak

# Build rule for target.
check_weak: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 check_weak
.PHONY : check_weak

# fast build rule for target.
check_weak/fast:
	$(MAKE) -f src/firmware/nuttx/CMakeFiles/check_weak.dir/build.make src/firmware/nuttx/CMakeFiles/check_weak.dir/build
.PHONY : check_weak/fast

#=============================================================================
# Target rules for targets named collect_extras

# Build rule for target.
collect_extras: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 collect_extras
.PHONY : collect_extras

# fast build rule for target.
collect_extras/fast:
	$(MAKE) -f src/firmware/nuttx/CMakeFiles/collect_extras.dir/build.make src/firmware/nuttx/CMakeFiles/collect_extras.dir/build
.PHONY : collect_extras/fast

#=============================================================================
# Target rules for targets named debug

# Build rule for target.
debug: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 debug
.PHONY : debug

# fast build rule for target.
debug/fast:
	$(MAKE) -f src/firmware/nuttx/CMakeFiles/debug.dir/build.make src/firmware/nuttx/CMakeFiles/debug.dir/build
.PHONY : debug/fast

#=============================================================================
# Target rules for targets named debug_ddd

# Build rule for target.
debug_ddd: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 debug_ddd
.PHONY : debug_ddd

# fast build rule for target.
debug_ddd/fast:
	$(MAKE) -f src/firmware/nuttx/CMakeFiles/debug_ddd.dir/build.make src/firmware/nuttx/CMakeFiles/debug_ddd.dir/build
.PHONY : debug_ddd/fast

#=============================================================================
# Target rules for targets named debug_io

# Build rule for target.
debug_io: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 debug_io
.PHONY : debug_io

# fast build rule for target.
debug_io/fast:
	$(MAKE) -f src/firmware/nuttx/CMakeFiles/debug_io.dir/build.make src/firmware/nuttx/CMakeFiles/debug_io.dir/build
.PHONY : debug_io/fast

#=============================================================================
# Target rules for targets named debug_io_ddd

# Build rule for target.
debug_io_ddd: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 debug_io_ddd
.PHONY : debug_io_ddd

# fast build rule for target.
debug_io_ddd/fast:
	$(MAKE) -f src/firmware/nuttx/CMakeFiles/debug_io_ddd.dir/build.make src/firmware/nuttx/CMakeFiles/debug_io_ddd.dir/build
.PHONY : debug_io_ddd/fast

#=============================================================================
# Target rules for targets named debug_io_tui

# Build rule for target.
debug_io_tui: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 debug_io_tui
.PHONY : debug_io_tui

# fast build rule for target.
debug_io_tui/fast:
	$(MAKE) -f src/firmware/nuttx/CMakeFiles/debug_io_tui.dir/build.make src/firmware/nuttx/CMakeFiles/debug_io_tui.dir/build
.PHONY : debug_io_tui/fast

#=============================================================================
# Target rules for targets named debug_tui

# Build rule for target.
debug_tui: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 debug_tui
.PHONY : debug_tui

# fast build rule for target.
debug_tui/fast:
	$(MAKE) -f src/firmware/nuttx/CMakeFiles/debug_tui.dir/build.make src/firmware/nuttx/CMakeFiles/debug_tui.dir/build
.PHONY : debug_tui/fast

#=============================================================================
# Target rules for targets named firmware_nuttx

# Build rule for target.
firmware_nuttx: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 firmware_nuttx
.PHONY : firmware_nuttx

# fast build rule for target.
firmware_nuttx/fast:
	$(MAKE) -f src/firmware/nuttx/CMakeFiles/firmware_nuttx.dir/build.make src/firmware/nuttx/CMakeFiles/firmware_nuttx.dir/build
.PHONY : firmware_nuttx/fast

#=============================================================================
# Target rules for targets named romfs

# Build rule for target.
romfs: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 romfs
.PHONY : romfs

# fast build rule for target.
romfs/fast:
	$(MAKE) -f src/firmware/nuttx/CMakeFiles/romfs.dir/build.make src/firmware/nuttx/CMakeFiles/romfs.dir/build
.PHONY : romfs/fast

#=============================================================================
# Target rules for targets named upload

# Build rule for target.
upload: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 upload
.PHONY : upload

# fast build rule for target.
upload/fast:
	$(MAKE) -f src/firmware/nuttx/CMakeFiles/upload.dir/build.make src/firmware/nuttx/CMakeFiles/upload.dir/build
.PHONY : upload/fast

#=============================================================================
# Target rules for targets named __nuttx_copy_px4io-v2

# Build rule for target.
__nuttx_copy_px4io-v2: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 __nuttx_copy_px4io-v2
.PHONY : __nuttx_copy_px4io-v2

# fast build rule for target.
__nuttx_copy_px4io-v2/fast:
	$(MAKE) -f src/modules/px4iofirmware/CMakeFiles/__nuttx_copy_px4io-v2.dir/build.make src/modules/px4iofirmware/CMakeFiles/__nuttx_copy_px4io-v2.dir/build
.PHONY : __nuttx_copy_px4io-v2/fast

#=============================================================================
# Target rules for targets named __nuttx_patch_px4io-v2

# Build rule for target.
__nuttx_patch_px4io-v2: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 __nuttx_patch_px4io-v2
.PHONY : __nuttx_patch_px4io-v2

# fast build rule for target.
__nuttx_patch_px4io-v2/fast:
	$(MAKE) -f src/modules/px4iofirmware/CMakeFiles/__nuttx_patch_px4io-v2.dir/build.make src/modules/px4iofirmware/CMakeFiles/__nuttx_patch_px4io-v2.dir/build
.PHONY : __nuttx_patch_px4io-v2/fast

#=============================================================================
# Target rules for targets named fw_io

# Build rule for target.
fw_io: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 fw_io
.PHONY : fw_io

# fast build rule for target.
fw_io/fast:
	$(MAKE) -f src/modules/px4iofirmware/CMakeFiles/fw_io.dir/build.make src/modules/px4iofirmware/CMakeFiles/fw_io.dir/build
.PHONY : fw_io/fast

#=============================================================================
# Target rules for targets named io_prebuild_targets

# Build rule for target.
io_prebuild_targets: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 io_prebuild_targets
.PHONY : io_prebuild_targets

# fast build rule for target.
io_prebuild_targets/fast:
	$(MAKE) -f src/modules/px4iofirmware/CMakeFiles/io_prebuild_targets.dir/build.make src/modules/px4iofirmware/CMakeFiles/io_prebuild_targets.dir/build
.PHONY : io_prebuild_targets/fast

#=============================================================================
# Target rules for targets named nuttx_export_px4io-v2

# Build rule for target.
nuttx_export_px4io-v2: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 nuttx_export_px4io-v2
.PHONY : nuttx_export_px4io-v2

# fast build rule for target.
nuttx_export_px4io-v2/fast:
	$(MAKE) -f src/modules/px4iofirmware/CMakeFiles/nuttx_export_px4io-v2.dir/build.make src/modules/px4iofirmware/CMakeFiles/nuttx_export_px4io-v2.dir/build
.PHONY : nuttx_export_px4io-v2/fast

#=============================================================================
# Target rules for targets named px4io-v2_default

# Build rule for target.
px4io-v2_default: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 px4io-v2_default
.PHONY : px4io-v2_default

# fast build rule for target.
px4io-v2_default/fast:
	$(MAKE) -f src/modules/px4iofirmware/CMakeFiles/px4io-v2_default.dir/build.make src/modules/px4iofirmware/CMakeFiles/px4io-v2_default.dir/build
.PHONY : px4io-v2_default/fast

# Help Target
help:
	@echo "The following are some of the valid targets for this Makefile:"
	@echo "... all (the default if no target is provided)"
	@echo "... clean"
	@echo "... depend"
	@echo "... __nuttx_copy_px4fmu-v2"
	@echo "... __nuttx_patch_px4fmu-v2"
	@echo "... edit_cache"
	@echo "... git_dspal"
	@echo "... git_eigen"
	@echo "... git_gencpp"
	@echo "... git_genmsg"
	@echo "... git_gtest"
	@echo "... git_mavlink"
	@echo "... git_nuttx"
	@echo "... git_uavcan"
	@echo "... install"
	@echo "... install/local"
	@echo "... install/strip"
	@echo "... list_install_components"
	@echo "... msg_gen"
	@echo "... nuttx_export_px4fmu-v2"
	@echo "... package"
	@echo "... package_source"
	@echo "... prebuild_targets"
	@echo "... rebuild_cache"
	@echo "... sercon"
	@echo "... serdis"
	@echo "... submodule_clean"
	@echo "... test"
	@echo "... xml_gen"
	@echo "... drivers__device"
	@echo "... drivers__stm32"
	@echo "... drivers__stm32__adc"
	@echo "... drivers__stm32__tone_alarm"
	@echo "... drivers__led"
	@echo "... drivers__px4fmu"
	@echo "... drivers__px4io"
	@echo "... drivers__boards__px4fmu-v2"
	@echo "... drivers__rgbled"
	@echo "... drivers__mpu6000"
	@echo "... drivers__mpu9250"
	@echo "... drivers__lsm303d"
	@echo "... drivers__l3gd20"
	@echo "... drivers__hmc5883"
	@echo "... drivers__ms5611"
	@echo "... drivers__mb12xx"
	@echo "... drivers__sf0x"
	@echo "... drivers__ll40ls"
	@echo "... drivers__trone"
	@echo "... drivers__gps"
	@echo "... drivers__pwm_out_sim"
	@echo "... drivers__hott"
	@echo "... drivers__hott__hott_telemetry"
	@echo "... drivers__hott__hott_sensors"
	@echo "... drivers__blinkm"
	@echo "... drivers__airspeed"
	@echo "... drivers__ets_airspeed"
	@echo "... drivers__meas_airspeed"
	@echo "... drivers__frsky_telemetry"
	@echo "... modules__sensors"
	@echo "... drivers__mkblctrl"
	@echo "... drivers__px4flow"
	@echo "... drivers__oreoled"
	@echo "... drivers__gimbal"
	@echo "... drivers__pwm_input"
	@echo "... drivers__camera_trigger"
	@echo "... systemcmds__bl_update"
	@echo "... systemcmds__mixer"
	@echo "... systemcmds__param"
	@echo "... systemcmds__perf"
	@echo "... systemcmds__pwm"
	@echo "... systemcmds__esc_calib"
	@echo "... systemcmds__reboot"
	@echo "... generate_topic_listener"
	@echo "... systemcmds__topic_listener"
	@echo "... systemcmds__top"
	@echo "... systemcmds__config"
	@echo "... systemcmds__nshterm"
	@echo "... systemcmds__mtd"
	@echo "... systemcmds__dumpfile"
	@echo "... systemcmds__ver"
	@echo "... modules__commander"
	@echo "... modules__navigator"
	@echo "... modules__mavlink"
	@echo "... modules__gpio_led"
	@echo "... modules__uavcan"
	@echo "... libuavcan_dsdlc"
	@echo "... uavcan"
	@echo "... uavcan_stm32_driver"
	@echo "... modules__land_detector"
	@echo "... modules__attitude_estimator_q"
	@echo "... modules__ekf_att_pos_estimator"
	@echo "... modules__position_estimator_inav"
	@echo "... modules__anfis_att_control"
	@echo "... modules__fw_pos_control_l1"
	@echo "... modules__fw_att_control"
	@echo "... modules__mc_att_control"
	@echo "... modules__mc_pos_control"
	@echo "... modules__vtol_att_control"
	@echo "... modules__sdlog2"
	@echo "... modules__param"
	@echo "... modules__systemlib"
	@echo "... mixer_gen"
	@echo "... modules__systemlib__mixer"
	@echo "... modules__controllib"
	@echo "... modules__uORB"
	@echo "... modules__dataman"
	@echo "... lib__mathlib"
	@echo "... lib__mathlib__math__filter"
	@echo "... lib__ecl"
	@echo "... lib__external_lgpl"
	@echo "... lib__geo"
	@echo "... lib__geo_lookup"
	@echo "... lib__conversion"
	@echo "... lib__launchdetection"
	@echo "... platforms__nuttx"
	@echo "... platforms__common"
	@echo "... platforms__nuttx__px4_layer"
	@echo "... modules__bottle_drop"
	@echo "... examples__rover_steering_control"
	@echo "... build_firmware_px4fmu-v2"
	@echo "... check_weak"
	@echo "... collect_extras"
	@echo "... debug"
	@echo "... debug_ddd"
	@echo "... debug_io"
	@echo "... debug_io_ddd"
	@echo "... debug_io_tui"
	@echo "... debug_tui"
	@echo "... firmware_nuttx"
	@echo "... romfs"
	@echo "... upload"
	@echo "... __nuttx_copy_px4io-v2"
	@echo "... __nuttx_patch_px4io-v2"
	@echo "... fw_io"
	@echo "... io_prebuild_targets"
	@echo "... nuttx_export_px4io-v2"
	@echo "... px4io-v2_default"
.PHONY : help



#=============================================================================
# Special targets to cleanup operation of make.

# Special rule to run CMake to check the build system integrity.
# No rule that depends on this can have commands that come from listfiles
# because they might be regenerated.
cmake_check_build_system:
	$(CMAKE_COMMAND) -H$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR) --check-build-system CMakeFiles/Makefile.cmake 0
.PHONY : cmake_check_build_system

